### ISSUE TITLE
Added smbambling as co-owener of sensu-plugins-tomcat repository

### ISSUE THREAD

**Issue by smbambling** [sensu-plugins/sensu-plugins-tomcat#3]
Can you please add me as a co-owner to this repository

**Comment by majormoses** [comment]
I sent an invite to be a collaborator with write access (only could do that since I created the repo and would not have access to do so on existing repos). Can we close this or do you really need admin? I would certainly not be comfortable giving you that without having a discussion with @mattyjones first.

**Comment by smbambling** [comment]
Nope write access should be more then plenty, my usage of co-owner was just incorrect. Thank you!
